import { Combine, DollarSign, Pickaxe, Leaf, ArrowRight, Users, ChevronRight, CheckCircle2 } from 'lucide-react';
import { Link } from 'react-router-dom';

// Simulated opportunities generated by the Spatial Clash Engine
const mockOpportunities = [
  {
    id: 'OPP-2026-001',
    location: 'Main Arterial Ave (Downtown Sector)',
    type: 'Joint Trenching',
    projects: [
      { id: 'PRJ-2026-104', title: 'Downtown Fiber Lay', agency: 'Telecom Infra', cost: 850000, layer: 'L3' },
      { id: 'PRJ-2026-199', title: 'Smart Grid Conduit', agency: 'Power Corp', cost: 620000, layer: 'L3' }
    ],
    savings: 340000,
    disruptionDaysSaved: 45,
    status: 'Pending Agency Review',
    matchScore: 92 // Percentage alignment in time/space
  },
  {
    id: 'OPP-2026-002',
    location: 'North Corridor',
    type: 'Sequential Dig & Fill',
    projects: [
      { id: 'PRJ-2026-089', title: 'North Corridor Trunk Main Upgrade', agency: 'Water Board', cost: 4200000, layer: 'L1' },
      { id: 'PRJ-2026-210', title: 'Stormwater Runoff Expansion', agency: 'Municipal Engineering', cost: 1100000, layer: 'L1' }
    ],
    savings: 580000,
    disruptionDaysSaved: 60,
    status: 'Co-Permit Initiated',
    matchScore: 88
  }
];

export default function Opportunities() {
  const formatCurrency = (val: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);

  return (
    <div className="flex flex-col h-full max-w-7xl mx-auto">
      
      {/* Page Header */}
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-slate-900 tracking-tight flex items-center gap-3">
          <Combine className="text-purple-600" size={32} />
          Co-Location Opportunities
        </h1>
        <p className="text-slate-500 text-sm mt-1">
          Automated "Dig Once" recommendations to share trenching costs and minimize public disruption.
        </p>
      </div>

      {/* Impact Summary Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        <div className="bg-gradient-to-br from-purple-600 to-purple-800 rounded-xl p-5 text-white shadow-md">
          <div className="flex items-center gap-3 mb-2 opacity-80">
            <DollarSign size={20} />
            <h3 className="font-semibold text-sm uppercase tracking-wider">Identified Savings</h3>
          </div>
          <p className="text-3xl font-black">{formatCurrency(920000)}</p>
          <p className="text-xs mt-2 opacity-80">Potential taxpayer funds saved in FY 2026-27</p>
        </div>

        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-3 mb-2 text-slate-500">
            <Pickaxe size={20} />
            <h3 className="font-semibold text-sm uppercase tracking-wider">Disruption Averted</h3>
          </div>
          <p className="text-3xl font-black text-slate-800">105 Days</p>
          <p className="text-xs mt-2 text-slate-400">Total road-closure days saved via joint cuts</p>
        </div>

        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-3 mb-2 text-slate-500">
            <Leaf size={20} />
            <h3 className="font-semibold text-sm uppercase tracking-wider">Carbon Reduction</h3>
          </div>
          <p className="text-3xl font-black text-slate-800">42 Tons</p>
          <p className="text-xs mt-2 text-slate-400">Estimated CO2 saved from heavy machinery</p>
        </div>
      </div>

      {/* Opportunities List */}
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-slate-800">Suggested Co-Permits (Active Matches)</h2>
      </div>

      <div className="grid gap-6">
        {mockOpportunities.map((opp) => (
          <div key={opp.id} className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden hover:shadow-md transition-all">
            {/* Card Header */}
            <div className="bg-slate-50 border-b border-slate-100 p-4 flex flex-wrap items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-full bg-purple-100 text-purple-600 flex items-center justify-center shrink-0 border border-purple-200">
                  <Combine size={24} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-900">{opp.location}</h3>
                  <div className="flex items-center gap-2 text-sm text-slate-500 mt-0.5">
                    <span className="font-medium text-purple-700 bg-purple-100 px-2 py-0.5 rounded text-xs">{opp.type}</span>
                    <span>• {opp.matchScore}% Spatial/Temporal Match</span>
                  </div>
                </div>
              </div>
              
              <div className="text-right">
                <p className="text-sm font-semibold text-emerald-600 mb-1">Est. Savings: {formatCurrency(opp.savings)}</p>
                <span className={`text-xs font-bold px-2.5 py-1 rounded-full border ${
                  opp.status === 'Co-Permit Initiated' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-amber-50 text-amber-700 border-amber-200'
                }`}>
                  {opp.status}
                </span>
              </div>
            </div>

            {/* Card Body: Project Split */}
            <div className="p-6">
              <div className="flex flex-col md:flex-row items-center gap-6">
                
                {/* Project A */}
                <div className="flex-1 w-full border border-slate-200 rounded-lg p-4 relative">
                  <span className="absolute -top-3 left-4 bg-white px-2 text-xs font-bold text-slate-400">Project A</span>
                  <div className="flex items-start justify-between">
                    <div>
                      <span className="text-xs font-bold bg-slate-800 text-white px-1.5 py-0.5 rounded mb-2 inline-block">{opp.projects[0].layer}</span>
                      <h4 className="font-bold text-slate-800">{opp.projects[0].title}</h4>
                      <p className="text-sm text-slate-500 flex items-center gap-1 mt-1"><Users size={14} /> {opp.projects[0].agency}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-semibold text-slate-600">{formatCurrency(opp.projects[0].cost)}</p>
                      <Link to={`/projects/${opp.projects[0].id}`} className="text-xs text-brand-primary hover:underline mt-1 inline-block">View</Link>
                    </div>
                  </div>
                </div>

                {/* Merge Icon */}
                <div className="hidden md:flex shrink-0 w-10 h-10 bg-slate-100 rounded-full items-center justify-center text-slate-400 z-10 border border-slate-200 shadow-sm">
                  <ArrowRight size={20} />
                </div>

                {/* Project B */}
                <div className="flex-1 w-full border border-slate-200 rounded-lg p-4 relative">
                  <span className="absolute -top-3 left-4 bg-white px-2 text-xs font-bold text-slate-400">Project B</span>
                  <div className="flex items-start justify-between">
                    <div>
                      <span className="text-xs font-bold bg-slate-800 text-white px-1.5 py-0.5 rounded mb-2 inline-block">{opp.projects[1].layer}</span>
                      <h4 className="font-bold text-slate-800">{opp.projects[1].title}</h4>
                      <p className="text-sm text-slate-500 flex items-center gap-1 mt-1"><Users size={14} /> {opp.projects[1].agency}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-semibold text-slate-600">{formatCurrency(opp.projects[1].cost)}</p>
                      <Link to={`/projects/${opp.projects[1].id}`} className="text-xs text-brand-primary hover:underline mt-1 inline-block">View</Link>
                    </div>
                  </div>
                </div>

              </div>
            </div>

            {/* Card Footer: Action Bar */}
            <div className="bg-slate-50 border-t border-slate-100 p-4 flex items-center justify-between">
              <p className="text-sm text-slate-500 italic">
                By combining trenches, agencies split excavation and backfill costs 50/50.
              </p>
              
              {opp.status === 'Co-Permit Initiated' ? (
                <button disabled className="px-4 py-2 bg-emerald-100 text-emerald-700 text-sm font-bold rounded-lg flex items-center gap-2 cursor-not-allowed">
                  <CheckCircle2 size={16} /> Workflow Active
                </button>
              ) : (
                <button className="px-4 py-2 bg-brand-primary text-white text-sm font-bold rounded-lg hover:bg-blue-700 flex items-center gap-2 transition-colors shadow-sm">
                  Initiate Co-Permit Workflow <ChevronRight size={16} />
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

    </div>
  );
}